#index:
#    path: /
#    controller: App\Controller\DefaultController::index


#app_lucky_number: #Name of the route to follow
#    path: /lucky/number
#    controller: App\Controller\LuckyController::number
